<?php

const TLBM_DIR = __DIR__;
const TLBM_PLUGIN_DIR = __DIR__;

const TLBM_MAIN_CSS_SLUG = "tlbm-main";
const TLBM_FRONTEND_JS_SLUG = "tlbm-script-frontend";
const TLBM_ADMIN_JS_SLUG = "tlbm-script-admin";

const TLBM_TEXT_DOMAIN = "booking-magic-plugin";
const TLBM_SHORTCODETAG_FORM = "booking_magic_form";
const TLBM_DELETE_DATA_ON_DEACTIVATION = false;

const TLBM_BOOKING_INTERNAL_STATE_PENDING   = "PENDING";
const TLBM_BOOKING_INTERNAL_STATE_COMPLETED = "COMPLETED";
const TLBM_BOOKING_DISTRIBUTION_EVENLY = "EVENLY";
const TLBM_BOOKING_DISTRIBUTION_FILL_ONE = "FILL ONE";

const TLBM_EXTDATETIME_INTERVAL_DAY = "INTERNAL_DAY";

const TLBM_ENTITY_ADMINSTATUS_ACTIVE  = "ACTIVE";
const TLBM_ENTITY_ADMINSTATUS_DELETED = "DELETED";

if(!defined("WP_PLUGIN_DIR")) {
    define("WP_PLUGIN_DIR", "");
}
