version: "3.7"

services:
  wordpress:
    image: wordpress:latest

    volumes:
    - ./:/var/www/html/wp-content/plugins/booking-magic

    ports:
    - 8080:80

    environment:
      WORDPRESS_DB_HOST: wordpress_database
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DEBUG: 1

  wordpress_database:
    image: mariadb

    volumes:
    - mariadb:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress_db

    ports:
    - 3336

volumes:
  mariadb: {}

