version: "3.7"

services:

  composer:
    image: composer
    restart: "no"
    volumes:
      - ./:/app

    environment:
      WORDPRESS_DB_HOST: wordpress_database_it
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DEBUG: 1
      TLBM_DEBUG: 1
      SCRIPT_DEBUG: 1
      WP_TESTS_DIR: /var/www/html

  #
  # WordPress Enviromnent for Development.
  # The site is available on localhost:8080 after the container starts.
  #
  wordpress:
    build: docker/dev
    restart: "no"
    volumes:
    - ./:/var/www/html/wp-content/plugins/booking-magic

    ports:
    - "8080:80"

    environment:
      WORDPRESS_DB_HOST: wordpress_database
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DEBUG: 1
      TLBM_DEBUG: 1

    depends_on:
      - wordpress_database

  #
  # MariaDB Service for WordPress Enviromnent
  #
  wordpress_database:
    image: mariadb
    restart: "no"
    volumes:
    - mariadb:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress_db

  wordpress_phpmyadmin:
    image: phpmyadmin
    restart: "no"
    environment:
      PMA_HOSTS: wordpress_database
      PMA_USER: dbuser
      PMA_PASSWORD: password
    ports:
    - "8081:80"

volumes:
  mariadb: {}

